### ISSUE TITLE
base directory missing when installing mdsine2

### ISSUE THREAD

**Issue by alejandrocs98** [gerberlab/MDSINE2#17]
When installing **mdsine2** using pip or conda, **base** directory (which is present in the GitHub repo) is not properly installed in the system. (This is easily manually fixed by copying the directory from the cloned git repo into the proper directory in the installation location, but I think it might cause problems eventually).

**Comment by yk23** [comment]
Hi alejandro.

This issue has been addressed in a development branch, which was planned to be merged & pending a new publication.
Please check out `cv-wip-mirror`, and should be merged in (see #19)

- youn

**Comment by yk23** [comment]
Dev branch to be merged into `master` sometime this week.

**Comment by yk23** [comment]
Addressed in PR #19, closing.
