### ISSUE TITLE
Question about data type

### ISSUE THREAD

**Issue by marcelladane** [gerberlab/MDSINE2#3]
Hey, I noticed that the pipeline uses a asv file.
And that the taxonomy table has the sequence information which is possible to get from a dada2 file. But if one wants to use metagenomics data, the sequences are not present, only the taxonomic classification. My question is, are the sequences needed to run the pipeline or one can still run without it?
Do you have any ideas of how to go around this issue?

Thanks. :)

**Comment by travisgibson** [comment]
Hi, you can run the model without the sequences. See our second tutorial in this repo https://github.com/gerberlab/MDSINE2_Paper/tree/master/google_colab
or you can open it directly in colab with this link https://colab.research.google.com/github/gerberlab/MDSINE2_Paper/blob/master/google_colab/tutorial2_inference.ipynb
